Fix race condition with orphan .disaster_recovery flag
bitnami/bitnami-docker-etcd pull request #20
Opened 2021-06-09 16:17 UTC by juan131

** Context **

There's an unlikely race condition in the [bitnami etcd chart](https://github.com/bitnami/charts/tree/master/bitnami/etcd) logic to recover from disasters that cause the last member to consider that it's not the last member. This happens when the last (N>1) members are recovering simultaneously.

The reason? The `.disaster_recovery flag` is left orphan in the shared volume causing problems during member initializations and `CrashLoopBackOff` errors since the last (N>1) members  do not consider they are "the last to recover from the disaster".

**Description of the change**

This changes the approach so the `.disaster_recovery` is not treated like a  simple semaphore, but instead it's used by the member discovering the disaster to communicate to the other members that they need to start the recovery process. This is done by writing the other members' names in the file.

When other members start and detect their name in the `.disaster_recovery` file, they remove their own name from the file until the last member removes the file considering the recovery process is finished.

**Benefits**

Reduces the % for the race condition to happen.

**Possible drawbacks**

None that I'm aware of

**Applicable issues**

Attempts to fix https://github.com/bitnami/charts/issues/6372

2021-06-10 07:21 UTC, rafariossaa requested changes

2021-06-10 07:21 UTC, rafariossaa commented on 3/debian-10/rootfs/opt/bitnami/scripts/libetcd.sh
> +            if [[ $(wc -w < "/snapshots/.disaster_recovery") -eq 0 ]]; then
should this be `wc -l` ?
I am asking because you are using `echo "$e" >> file` in line 286 and the `echo` will add `\n`.

2021-06-10 07:45 UTC, juan131 commented on 3/debian-10/rootfs/opt/bitnami/scripts/libetcd.sh
> +            if [[ $(wc -w < "/snapshots/.disaster_recovery") -eq 0 ]]; then
As you mentioned, the `echo` is adding a `\n`. As a consequence, once you remove the **etcd** members names from the file, the file remains empty with a `n`. `wc` consider it has 0 words, but it has one line. See this example:

```console
$ echo "foo" >> /tmp/bar
$ echo "baz" >> /tmp/bar
$ cat /tmp/bar
foo
baz
$ remove_in_file /tmp/bar "foo"
$ remove_in_file /tmp/bar "baz"
$ cat /tmp/bar

$ wc -w < /tmp/bar
       0
$ wc -l < /tmp/bar
       1
```

2021-06-10 07:56 UTC, rafariossaa commented on 3/debian-10/rootfs/opt/bitnami/scripts/libetcd.sh
> +            if [[ $(wc -w < "/snapshots/.disaster_recovery") -eq 0 ]]; then
Ok, thanks for the clarification.

LGTM

2021-06-10 07:56 UTC, rafariossaa approved these changes

2021-06-10 14:46 UTC, juan131 commented
@wnke do you see any cons with the proposal? Otherwise, I'll proceed to land the changes and release a new version of the etcd container/chart.

2021-06-11 10:26 UTC, merged

2021-06-11 12:23 UTC, juan131 commented
Changes were included at `3.4.16-debian-10-r25` image revision, see https://github.com/bitnami/bitnami-docker-etcd/commit/98f26b0c8f1789494d2090732caf3aeabe9f3ee0