Fix empty member ID
bitnami/bitnami-docker-etcd pull request #21
Opened 2021-08-23 08:32 UTC by ckoehn

**Context**

The cluster members are currently not reliably writing the member ID to their `member_id` file (see https://github.com/bitnami/charts/issues/6251). Since this is a crucial prerequisite to rejoin the cluster after a restart the nodes are not able to join the cluster again and end up in `CrashLoopBackOff`.

**Description of the change**
We traced it down to three individual problems:
* The logic to write the `member_id` fails if the current member is not in the cluster member list
* `wait_for_dns_lookup` is not a reliable guard to ensure consecutive queries are actually returning something. Occasionally the next query result was empty and `etcdctl_get_endpoints` returned an empty string.
* The prestop hook occasionally failed with `rpc error: code = Unavailable desc = etcdserver: server stopped` when the current member was part of the endpoints.

**Benefits**
The nodes are able to join the cluster after a restart.

**Applicable issues**
Closes https://github.com/bitnami/charts/issues/6251

**Additional information**
- k8s `v1.15.11`
- etcd chart `6.4.1`
- etcd image `3.5.0-debian-10-r57`

2021-08-23 15:09 UTC, juan131 reviewed
Thanks so much for this!

I don't have much time today to review this and I don't want to it this in a rush since this logic is quite complex and it's very easy to introduce backwards incompatibilities or race conditions that escape our eyes. I'll check it tomorrow morning (I'm based in Spain) thoroughly and with a good dose of coffee!

2021-08-23 20:23 UTC, ckoehn commented
Thanks @juan131. Looking forward to it. 

While researching the `wait_for_dns_lookup` problem I discovered https://stackoverflow.com/questions/62163360/redis-cluster-in-kubernetes-container-restarts-on-spinup which describes a similar problem.

2021-08-24 09:37 UTC, juan131 requested changes
Thanks again so much for your contribution! Please check my comments when you have a chance

2021-08-24 09:37 UTC, juan131 commented on 3/debian-10/rootfs/opt/bitnami/scripts/etcd/prestop.sh
> +endpoints="$(etcdctl_get_endpoints true)"
PreStop hooks are executed **BEFORE** the TERM signal to stop the container is sent (see [Container Lifecycle docs](https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/)). Therefore, why should we exclude the current member (which is running when this code is executed) from the list of endpoints to receive the "member remove" order?

2021-08-24 09:37 UTC, juan131 commented on 3/debian-10/rootfs/opt/bitnami/scripts/libetcd.sh
> +    }
This approach is very risky since it's likely to enter into an infinite loop. Instead, we can use our `retry_while` function (defined in the [libos.sh library](https://github.com/bitnami/bitnami-docker-etcd/blob/master/3/debian-10/prebuildfs/opt/bitnami/scripts/libos.sh#L269)):
```suggestion
    hostname_has_ips() {
       local hostname="${1:?hostname is required}"
       [[ "$(getent ahosts "$hostname")" != "" ]] && return 0
       return 1
    }
```
Suggestion follow in the next comment

2021-08-24 09:37 UTC, juan131 commented on 3/debian-10/rootfs/opt/bitnami/scripts/libetcd.sh
> +        for ip in $(get_ips "${domain}"); do
```suggestion
        if retry_while "hostname_has_ips $domain"; then
           for ip in $(getent ahosts "$domain" | awk '{print $1}' | uniq); do
```

2021-08-24 09:37 UTC, juan131 commented on 3/debian-10/rootfs/opt/bitnami/scripts/libetcd.sh
> +            etcdctl "${extra_flags[@]}" member list | grep -w "$ETCD_ADVERTISE_CLIENT_URLS" | awk -F "," '{ print $1}' > "${ETCD_DATA_DIR}/member_id" || true
Nice!

2021-08-24 20:35 UTC, ckoehn commented on 3/debian-10/rootfs/opt/bitnami/scripts/libetcd.sh
> +    }
I agree. The current implementation is not very safe in that regard. I tested your suggested change and it seems to work 👍🏻

2021-08-24 20:36 UTC, ckoehn commented on 3/debian-10/rootfs/opt/bitnami/scripts/libetcd.sh
> +        for ip in $(get_ips "${domain}"); do
I applied these changes manually to avoid a syntax error.

2021-08-24 20:49 UTC, ckoehn commented on 3/debian-10/rootfs/opt/bitnami/scripts/etcd/prestop.sh
> +endpoints="$(etcdctl_get_endpoints true)"
I double checked the container lifecycle docs too and I currently have no good explanation for this behavior. The PreStop hook failed less often during my tests when the current member was excluded. Let me conduct some more tests tomorrow to see if I can see a pattern.

2021-08-25 06:38 UTC, juan131 commented on 3/debian-10/rootfs/opt/bitnami/scripts/libetcd.sh
> +        for ip in $(get_ips "${domain}"); do
thanks

2021-08-25 07:19 UTC, juan131 commented on 3/debian-10/rootfs/opt/bitnami/scripts/etcd/prestop.sh
> +endpoints="$(etcdctl_get_endpoints true)"
It's very weird.. Reading **etcd** docs (see https://etcd.io/docs/v3.3/op-guide/runtime-configuration/#remove-a-member) I'm pretty sure the member to be removed should also receive the "member remove" order...

There's only one explanation for your approach to fail less often that comes to my mind:

- The PreStop hook sends the "member remove" order to the current member that's being stopped (also the rest of members).
- The member is stopped since it receives the order BUT the hook hasn't finished yet since it's waiting for the order to be completed (receive the confirmation from every member).
- The hook finished abruptly (before completing the command) since the termination grace period expire, and the "member_removal.log" isn't created.

However, I can't confirm that's happening since it's not aligned with [Pod Termination docs](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-termination)...

We can try playing with the **terminationGracePeriodSeconds** to see if that helps.. I created [this PR](https://github.com/bitnami/charts/pull/7307) to add this feature to the chart.

2021-09-01 06:12 UTC, juan131 commented
@ckoehn did you have any chance to play with terminationGracePeriodSeconds to see if that reduces the chances for the PreStop hook to fail?

2021-09-02 05:49 UTC, ckoehn commented
Sadly I haven‘t had time to check it in the last week, but I want to get back to this issue at the end of next week to conduct some more tests. Sorry for the delay. Will report back once I know more. 

> On 1. Sep 2021, at 08:13, Juan Ariza Toledano ***@***.***> wrote:
> 
> ﻿
> @ckoehn did you have any chance to play with terminationGracePeriodSeconds to see if that reduces the chances for the PreStop hook to fail?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.

2021-09-02 14:08 UTC, juan131 commented
All right! Thanks for the update

2021-09-10 05:09 UTC, danfromtitan commented
Tested the fix, I'm still experiencing "unhealthy cluster" when a new node gets added to an existing cluster but the member is still unstarted (member_id is empty in that case, I believe _etcd_store_member_id_ should get called [after member is added](https://github.com/ckoehn/bitnami-docker-etcd/blob/fix-empty-member-id/3/debian-10/rootfs/opt/bitnami/scripts/libetcd.sh#L383))

Also, scalling down the cluster I came across "member not found" - existing etcd-0 member was inadvertently removed from the cluster while it was still a legit member.

IMO the idea of relying on member_id file or data directory content to tell the status of the cluster is flawed and should be abandoned.

2021-09-10 07:28 UTC, juan131 commented
Thanks for your feedback @danfromtitan and testing @ckoehn's proposal! I really appreciate it.

> IMO the idea of relying on member_id file or data directory content to tell the status of the cluster is flawed and should be abandoned.

I agree there's room for improvement in this logic and we can make it much more resilient. The main challenge here is having a logic that's compatible with K8s and compose scenarios, and avoiding providing capabilities to talk with the K8s API. These are the main reasons why we decided to rely on the persistent data.

2021-09-10 15:32 UTC, danfromtitan commented on 3/debian-10/rootfs/opt/bitnami/scripts/libetcd.sh
> +                    h="$(getent hosts "$ip" | awk '{print $2}')"
There are couple of issues I came across when building the endpoints list like this:

- `getent hosts $ip` would return hostnames in different formats: etcd-2.etcd-headless.kv.svc.cluster.local versus 10-237-136-79.etcd.kv.svc.cluster.local; the issue with the later is the change in domain name, which comes into play when TLS verification is enabled. I had to add both *.etcd-headless.kv.svc.cluster.local and *.etcd.kv.svc.cluster.local to certificate SANs to make this work.
- the IPs returned from the headless service DNS record are for all PODs in the statefulset, regardless whether they are healthy cluster nodes or not. Not a big issue as etcdctl has the ability to try all nodes in the list to get a conection, but if you use endpoints in a more authoritative sense (i.e. determine cluster health or validate quorum), that might become a problem.

2021-09-10 18:06 UTC, danfromtitan commented on 3/debian-10/rootfs/opt/bitnami/scripts/etcd/prestop.sh
> +endpoints="$(etcdctl_get_endpoints true)"
> PreStop hooks are executed **BEFORE** the TERM signal to stop the container is sent (see [Container Lifecycle docs](https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/)). Therefore, why should we exclude the current member (which is running when this code is executed) from the list of endpoints to receive the "member remove" order?

True, however when the script process fails early the POD gets into an Error > CrashLoopback state and it gets restarted, not terminated. What I've seen often happens is etcdctl adds the member then script fails and POD restarts, but now the member is already added and the subsequent error when add member runs again is cluster is in unhealthy state. IMO there should be some logic added to libetcd.sh script to either cleanup the member or continue from where it has left.

2021-09-10 18:35 UTC, danfromtitan commented
> The main challenge here is having a logic that's compatible with K8s and compose scenarios, and avoiding providing capabilities to talk with the K8s API. These are the main reasons why we decided to rely on the persistent data.

I understand, I'm not familiar with how this image is used outside k8s, neither I know much about Bitnami's common libraries. I see some of these are used here but I don't know how they are used elsewhere.

It seems to me the decision to maintain your own persistent data outside etcdctl is what's causing us chasing these issues now. There's nothing wrong keeping persistent data at hand for verification purposes, but when you rely on that to make early decisions about the logic of the start-up script flow, that's where it starts going south. Then when that happens you find yourself wrestling corner cases with the script itself and there is not much room to literary bash your way out of it :)

Couple of examples to illustrate what I came across in my testing:

- checking whether [data dir is empty](https://github.com/bitnami/bitnami-docker-etcd/blob/master/3/debian-10/rootfs/opt/bitnami/scripts/libetcd.sh#L366) makes the assumption that if it's not, then it must come from a previous healthy node that was restarted. In my case the node had failed because of previous errors, data dir had only an empty new_member_envs file, but the check for an empty dir sets things on a different path than it should have been.

- in a similar way, different run this time, [member_id exists](https://github.com/bitnami/bitnami-docker-etcd/blob/master/3/debian-10/rootfs/opt/bitnami/scripts/libetcd.sh#L450) but was created empty, POD restarts after crash and now it find member_id file and fails because it's empty

I can go with more examples, but I'll stop saying I found myself chasing my tail around the libetcd.sh script because the decision making is based on flawed premises.

My suggestions for improvement:

- For the initial cluster creation you could use the headless DNS record to find the list of nodes, it's assumed during the initial creation that all nodes will come-up healthy. After that rely heavily on `etcdctl member list` to determine cluster members.

- Use member_id as a final verification step or a tiebreaker, never as the first meaning to establish cluster membership or the script course of action. Countless times I've seen member_id not created or empty while the node was sitting in the list of members in an unstarted state, thus ending in an "unhealthy cluster" error. To keep persistent data on disk you need to make sure the [memory buffers are flushed to disk](https://stackoverflow.com/questions/1429951/force-flushing-of-output-to-a-file-while-bash-script-is-still-running) before the script exists.

- Make dynamic etcdctl or curl API calls into the cluster members to make decisions about the script flow, rather than rely on decisions made earlier in the process that might not reflect reality at the time.

- Changes in container env vars [I mentioned]( https://github.com/bitnami/charts/issues/6251#issuecomment-916636099) terminate the healthy member, resulting in prestop.sh script run which removes the member just to get it added again when the POD comes back. That affects the cluster quorum, not to mention the possibility that start-up script goes wrong and the node is left in a crash loop. I'd think the restarting member should be left alone, etcd has the ability to recover from node restarts (PVC volume is there to preserve the data), while a cronjob would be better suited to [cleanup members]( https://etcd.io/docs/v2.3/admin_guide/#lifecycle) that are lingering around for too long.

2021-09-13 07:24 UTC, juan131 commented
Hi @danfromtitan 

Thanks so much for your analysis & suggestions, they're priceless!!

> For the initial cluster creation you could use the headless DNS record to find the list of nodes, it's assumed during the initial creation that all nodes will come-up healthy. After that rely heavily on `etcdctl member list` to determine cluster members.

That would only work on the K8s scenario. That said, we already have a `ETCD_ON_K8S` env. variable that allows us to apply certain logic only when running the container on k8s. For instance, check the example below:

- https://github.com/bitnami/bitnami-docker-etcd/blob/master/3/debian-10/rootfs/opt/bitnami/scripts/libetcd.sh#L122

As you can see in that example, we're already using the headless DNS record to find the list of nodes. So, I guess you're suggesting stop relying on `ETCD_INITIAL_CLUSTER` in the `etcd_initialize` function at all... Which is more or less equivalent to invoking `recalculate_initial_cluster` also when bootstrapping a new cluster. Am I right?

> Use member_id as a final verification step or a tiebreaker, never as the first meaning to establish cluster membership or the script course of action. Countless times I've seen member_id not created or empty while the node was sitting in the list of members in an unstarted state, thus ending in an "unhealthy cluster" error. To keep persistent data on disk you need to make sure the [memory buffers are flushed to disk](https://stackoverflow.com/questions/1429951/force-flushing-of-output-to-a-file-while-bash-script-is-still-running) before the script exits.

I love the idea of using [stdbuf](https://www.gnu.org/software/coreutils/manual/html_node/stdbuf-invocation.html#stdbuf-invocation) to ensure memory buffers are flushed to disk so we reduce the chances that the "member_id" is not created. We simply need to modify the line below @ckoehn:

- https://github.com/bitnami/bitnami-docker-etcd/blob/master/3/debian-10/rootfs/opt/bitnami/scripts/libetcd.sh#L188

Also, I agree on making our decision making less dependent on the information saved on this file.

> Make dynamic etcdctl or curl API calls into the cluster members to make decisions about the script flow, rather than rely on decisions made earlier in the process that might not reflect reality at the time

I'd say that we're already doing so @danfromtitan since we're calling `etcdctl_get_endpoints` continuously before making decisions.

> Changes in container env vars [I mentioned](https://github.com/bitnami/charts/issues/6251#issuecomment-916636099) terminate the healthy member, resulting in prestop.sh script run which removes the member just to get it added again when the POD comes back. That affects the cluster quorum, not to mention the possibility that start-up script goes wrong and the node is left in a crash loop. I'd think the restarting member should be left alone, etcd has the ability to recover from node restarts (PVC volume is there to preserve the data), while a cronjob would be better suited to [cleanup members](https://etcd.io/docs/v2.3/admin_guide/#lifecycle) that are lingering around for too long.

The good thing is that we're exposing a `removeMemberOnContainerTermination` parameter in the chart so users can decide whether using this `prestop.sh` script or not. See:

- https://github.com/bitnami/charts/blob/master/bitnami/etcd/values.yaml#L186

The main challenge I find on using a "cronjob" approach is adapting the schedule to very different situations that might require removing members with more or less frequency.

2021-09-13 15:39 UTC, danfromtitan commented
> So, I guess you're suggesting stop relying on ETCD_INITIAL_CLUSTER in the etcd_initialize function at all... Which is more or less equivalent to invoking recalculate_initial_cluster also when bootstrapping a new cluster. Am I right?

ETCD_INITIAL_CLUSTER [must be set](https://etcd.io/docs/v3.3/op-guide/runtime-configuration/#add-a-new-member) for etcdctl to add new members, it's not like it can be ignored. To avoid the re-creation of PODs in k8s, ETCD_INITIAL_CLUSTER and ETCD_INITIAL_CLUSTER_STATE should be set from the libetcd script though. You can still utilize these container env vars for docker-compose and set them from docker-compose-cluster.yml like you do now, but in k8s leave them empty and in the libetcd if they come empty, then create them based on headless service or cluster members. 

> That said, we already have a ETCD_ON_K8S env. variable that allows us to apply certain logic only when running the container on k8s. 

True, that could be leveraged to split the logic path between k8s and composer.

I need to raise a flag though because what we talked about doing so far doesn't quite align with container image best practices. We're cramming too much logic in the container image about how that image is going to be consumed in k8s. Usually the image scripts should cover etcd functionality use-cases when the image is only deployed with composer. So satisfy k8s deployment requirements (i.e. create ETCD_INITIAL_CLUSTER and ETCD_INITIAL_CLUSTER_STATE env vars, provide a script for prestop hook etc.) you would use init containers, which would add the scripts needed for k8s deployment that are missing from the container image. That way you'd have a clean cut between deployment requirements and even between projects, making these easier to maintain.

> The good thing is that we're exposing a removeMemberOnContainerTermination parameter in the chart

Thank you, I didn't notice that until now.

> The main challenge I find on using a "cronjob" approach is adapting the schedule to very different situations that might require removing members with more or less frequency.

Yes, same here. I still like the PreStop hook especially because the POD would likely get a new IP address when it's re-created, so it's a nice way to start refresh. Especially when the node resolves with an IP address in name (i.e. 10-237-136-79.etcd.kv.svc.cluster.local) the old name might linger around for some time unless it's removed. I guess if we prevent the nodes to be re-created every helm chart upgrade, the PreStop hook is a viable path.

2021-09-14 06:46 UTC, juan131 commented
> ETCD_INITIAL_CLUSTER must be set for etcdctl to add new members, it's not like it can be ignored. To avoid the re-creation of PODs in k8s, ETCD_INITIAL_CLUSTER and ETCD_INITIAL_CLUSTER_STATE should be set from the libetcd script though

Correct, that's why I suggested invoking `recalculate_initial_cluster` also when bootstrapping a new cluster. See an example of using this function when recovering from losing the quorum:

- https://github.com/bitnami/bitnami-docker-etcd/blob/master/3/debian-10/rootfs/opt/bitnami/scripts/libetcd.sh#L319
- https://github.com/bitnami/bitnami-docker-etcd/blob/master/3/debian-10/rootfs/opt/bitnami/scripts/libetcd.sh#L427

> We're cramming too much logic in the container image about how that image is going to be consumed in k8s (...) satisfy k8s deployment requirements (...) you would use init containers, which would add the scripts needed for k8s deployment that are missing from the container image. 

In the past the logic for K8s was mounted on from a ConfigMap containing the required scripts. This ConfigMap was only available in the chart, keeping the image simpler. However, we decided to move the logic to the container.

The reason: it was a pain maintaining these scripts in the chart side. We had no proper linters and it required to be rendering the chart manifests continuously to see the actual bash code since it was mixing bash logic and `if/else` conditions from the Helm template language.

2021-09-21 06:38 UTC, juan131 commented
@ckoehn did you have a chance to take a look to the concerns shared by @danfromtita? Are you okay if I contribute to your PR so we can give this a little push and move forward?

We understand this can be very time consuming, and I'd like to personally thank you for the effort you're doing investigating this issue and proposing a solution.

2021-09-21 20:42 UTC, ckoehn commented
@juan131 Thanks for reaching out. Unfortunately I currently have no time to work on this issue. Feel free to contribute or even start from scratch if you think it's necessary. I will definitely get back to it, because it's an important part of our software stack.

2021-09-22 09:48 UTC, juan131 commented
All right! Thanks @ckoehn 

I'll update this PR so the changes you did keep your authorship.

2021-10-08 08:57 UTC, kuznero commented
@ondrej-smola sounds great! I will be running some tests from my side to validate it too later today.

2021-10-08 11:21 UTC, silvajp2 commented
I am also testing the `juanariza131/etcd:3` image. But unfortunately i am still getting the the error:
```
etcd 11:12:45.82                                                                                                                                                                                                           
etcd 11:12:45.82 Welcome to the Bitnami etcd container                                                                                                                                                                     
etcd 11:12:45.82 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-etcd                                                                                                                   
etcd 11:12:45.82 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-etcd/issues                                                                                                               
etcd 11:12:45.82                                                                                                                                                                                                           
etcd 11:12:45.83 INFO  ==> ** Starting etcd setup **                                                                                                                                                                       
etcd 11:12:45.84 INFO  ==> Validating settings in ETCD_* env vars..                                                                                                                                                        
etcd 11:12:45.84 WARN  ==> You set the environment variable ALLOW_NONE_AUTHENTICATION=yes. For safety reasons, do not use this flag in a production environment.                                                           
etcd 11:12:45.85 INFO  ==> Initializing etcd                                                                                                                                                                               
etcd 11:12:45.86 INFO  ==> Detected data from previous deployments                                                                                                                                                         
etcd 11:12:51.05 INFO  ==> Updating member in existing cluster                                                                                                                                                             
Error: bad member ID arg (strconv.ParseUint: parsing "": invalid syntax), expecting ID in Hex                                                                                                                              
```

This cluster was previously running on the official bitnami image and was upgraded via helm. After the upgrade all the PVCs were deleted and the cluster booted from the snapshot backup. 

Killing the erroed pod does not help, I have not yet tried to delete pvc and restart.

my values.yaml:
```
nameOverride: etcd-cluster
image:
  repository: juanariza131/etcd
  tag: 3
  pullPolicy: Always

podAnnotations:
  sidecar.istio.io/inject: "false"

podSecurityContext:
  enabled: true
  fsGroup: 1337

containerSecurityContext:
  enabled: true
  runAsUser: 1337
  runAsNonRoot: true

auth:
  rbac: 
    enabled: false
    allowNoneAuthentication: true
autoCompactionRetention: 12
autoCompactionMode: periodic

replicaCount: 5

containerPorts:
  client: 2379
  peer: 2380

resources:
  limits: {}
  requests: 
    cpu: 500m
    memory: 1Gi

livenessProbe:
  enabled: true
  initialDelaySeconds: 60
  periodSeconds: 30
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 5
readinessProbe:
  enabled: true
  initialDelaySeconds: 45
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 5
startupProbe:
  enabled: false
  initialDelaySeconds: 0
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 60

podAntiAffinityPreset: soft

pdb:
  create: true
  minAvailable: 3
  maxUnavailable: 0

persistence:
  enabled: true
  annotations: {}
  ## Persistent Volume Access Modes
  ##
  accessModes:
    - ReadWriteOnce
  ## Persistent Volume size
  ##
  size: 8Gi
  ## Provide any additional label selector to further filter the set of volumes (evaluated as a template)
  ## ref: https://kubernetes.io/docs/concepts/storage/persistent-volumes/#selector
  ##
  selector: {}

metrics:
  enabled: true
  ## Annotations for the Prometheus metrics on etcd pods
  ##
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "2379"

volumePermissions:
  enabled: true
disasterRecovery:
  enabled: true
  cronjob:
    schedule: "*/30 * * * *"

    historyLimit: 3

    snapshotHistoryLimit: 50

    podAnnotations: 
      sidecar.istio.io/inject: "false"

    resources:

      limits: {}
      requests: {}
  pvc:
    existingClaim: etcd-nfs-pvc

```

2021-10-08 12:04 UTC, silvajp2 commented
@ondrej-smola Thanks for getting back to me! Here the steps I took:

1. helm upgrade to new image
1.1 new pods got stuck
2. delete all pods and pvcs
3. boot from snapshot: all good!
3.1 kill random pods: all good
4. Increase replicas 3 -> 5 via helm: all good!
4.1 kill random pods: all good
5. delete random pod[after some time]: `Error: bad member ID arg (strconv.ParseUint: parsing "": invalid syntax), expecting ID in Hex`
6. delete all pods and pvcs
7. boot from snapshot: all good!

Since step 7, I have been randomly have not been able to reproduce the issue but I will keep killing pods for a while and try.

2021-10-08 14:15 UTC, smartbit commented
> This pull request does not handle "recovery" from the invalid state just fixes entering this state in the future.

@ondrej-smola Thanks for the clarification. After changing `juanariza131/etcd:3` I wasn't able to add a `Crashlooping` member to a cluster initialized with the [default images](https://github.com/bitnami/charts/blob/master/bitnami/etcd/values.yaml#L71-L72). Then tried
- scale to 0 
- delete all PVC & PV
- scale to 3
- cluster works fine
- scale to 0 
- delete PVC/PV of etcd-0
- scale to 3
- PVC/PV for etcd-0 get created 
- after some initial restarts, cluster stable

2021-10-11 10:28 UTC, ondrej-smola commented
@juan131 I was unable to reproduce as I was using older 6.5.0 - I am able to reproduce it in 6.9.0. @danfromtitan could you please try 6.5.0 to ack? Thank you

2021-10-11 10:34 UTC, ondrej-smola commented
also unable to reproduce with 6.8.4 .... it seems like it was introduced last weekend in 6.9.0

2021-10-12 11:29 UTC, ondrej-smola commented
when i turned disaster recovery off and hit the case with "detecting data from previous deployments" the cluster recovers after some time

> etcd 11:25:24.20
etcd 11:25:24.20 Welcome to the Bitnami etcd container
etcd 11:25:24.20 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-etcd
etcd 11:25:24.20 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-etcd/issues
etcd 11:25:24.20
etcd 11:25:24.20 INFO  ==> ** Starting etcd setup **
etcd 11:25:24.22 INFO  ==> Validating settings in ETCD_* env vars..
etcd 11:25:24.22 INFO  ==> Initializing etcd
etcd 11:25:24.23 INFO  ==> Detected data from previous deployments
etcd 11:25:28.29 WARN  ==> Cluster not responding!
etcd 11:25:28.29 WARN  ==> Disaster recovery is disabled, the cluster will try to recover on it's own
etcd 11:25:28.29 INFO  ==> ** etcd setup finished! **

etcd 11:25:28.34 INFO  ==> ** Starting etcd **
{"level":"info","ts":1634037928.3625946,"caller":"flags/flag.go:113","msg":"recognized and used environment variable","variable-name":"ETCD_ADVERTISE_CLIENT_URLS","variable-value":"http://etcd-test-1.etcd-test-headless.ng-etcd.svc.cluster.local:2379"}
{"level":"info","ts":1634037928.362652,"caller":"flags/flag.go:113","msg":"recognized and used environment variable","variable-name":"ETCD_AUTH_TOKEN","variable-value":"jwt,priv-key=/opt/bitnami/etcd/certs/token/jwt-token.pem,sign-method=RS256,ttl=10m"}
{"level":"info","ts":1634037928.3626635,"caller":"flags/flag.go:113","msg":"recognized and used environment variable","variable-name":"ETCD_AUTO_TLS","variable-value":"false"}
{"level":"info","ts":1634037928.3626752,"caller":"flags/flag.go:113","msg":"recognized and used environment variable","variable-name":"ETCD_CLIENT_CERT_AUTH","variable-value":"false"}
{"level":"info","ts":1634037928.3626873,"caller":"flags/flag.go:113","msg":"recognized and used environment variable","variable-name":"ETCD_DATA_DIR","variable-value":"/bitnami/etcd/data"}
{"level":"info","ts":1634037928.3627365,"caller":"flags/flag.go:113","msg":"recognized and used environment variable","variable-name":"ETCD_INITIAL_ADVERTISE_PEER_URLS","variable-value":"http://etcd-test-1.etcd-test-headless.ng-etcd.svc.cluster.local:2380"}
{"level":"info","ts":1634037928.362745,"caller":"flags/flag.go:113","msg":"recognized and used environment variable","variable-name":"ETCD_INITIAL_CLUSTER","variable-value":"etcd-test-1=http://etcd-test-1.etcd-test-headless.ng-etcd.svc.cluster.local:2380,etcd-test-0=http://etcd-test-0.etcd-test-headless.ng-etcd.svc.cluster.local:2380,etcd-test-2=http://etcd-test-2.etcd-test-headless.ng-etcd.svc.cluster.local:2380"}
{"level":"info","ts":1634037928.3627536,"caller":"flags/flag.go:113","msg":"recognized and used environment variable","variable-name":"ETCD_INITIAL_CLUSTER_STATE","variable-value":"new"}
{"level":"info","ts":1634037928.3627667,"caller":"flags/flag.go:113","msg":"recognized and used environment variable","variable-name":"ETCD_INITIAL_CLUSTER_TOKEN","variable-value":"etcd-cluster-k8s"}
{"level":"info","ts":1634037928.362779,"caller":"flags/flag.go:113","msg":"recognized and used environment variable","variable-name":"ETCD_LISTEN_CLIENT_URLS","variable-value":"http://0.0.0.0:2379"}
{"level":"info","ts":1634037928.3627877,"caller":"flags/flag.go:113","msg":"recognized and used environment variable","variable-name":"ETCD_LISTEN_PEER_URLS","variable-value":"http://0.0.0.0:2380"}
{"level":"info","ts":1634037928.3627968,"caller":"flags/flag.go:113","msg":"recognized and used environment variable","variable-name":"ETCD_LOG_LEVEL","variable-value":"info"}
{"level":"info","ts":1634037928.3628085,"caller":"flags/flag.go:113","msg":"recognized and used environment variable","variable-name":"ETCD_NAME","variable-value":"etcd-test-1"}
{"level":"info","ts":1634037928.3628209,"caller":"flags/flag.go:113","msg":"recognized and used environment variable","variable-name":"ETCD_PEER_AUTO_TLS","variable-value":"false"}
{"level":"warn","ts":1634037928.3628519,"caller":"flags/flag.go:93","msg":"unrecognized environment variable","environment-variable":"ETCD_TRUSTED_CA_FILE="}
{"level":"warn","ts":1634037928.3628628,"caller":"flags/flag.go:93","msg":"unrecognized environment variable","environment-variable":"ETCD_TEST_SERVICE_PORT_CLIENT=2379"}
{"level":"warn","ts":1634037928.362869,"caller":"flags/flag.go:93","msg":"unrecognized environment variable","environment-variable":"ETCD_TEST_PORT_2380_TCP_PORT=2380"}
{"level":"warn","ts":1634037928.3628743,"caller":"flags/flag.go:93","msg":"unrecognized environment variable","environment-variable":"ETCD_TEST_PORT_2380_TCP_ADDR=10.20.167.3"}
{"level":"warn","ts":1634037928.3628805,"caller":"flags/flag.go:93","msg":"unrecognized environment variable","environment-variable":"ETCD_ON_K8S=yes"}
{"level":"warn","ts":1634037928.3628857,"caller":"flags/flag.go:93","msg":"unrecognized environment variable","environment-variable":"ETCD_TEST_PORT_2379_TCP=tcp://10.20.167.3:2379"}
{"level":"warn","ts":1634037928.362891,"caller":"flags/flag.go:93","msg":"unrecognized environment variable","environment-variable":"ETCD_SNAPSHOTS_DIR=/snapshots"}
{"level":"warn","ts":1634037928.3628967,"caller":"flags/flag.go:93","msg":"unrecognized environment variable","environment-variable":"ETCD_BIN_DIR=/opt/bitnami/etcd/sbin"}
{"level":"warn","ts":1634037928.3629017,"caller":"flags/flag.go:93","msg":"unrecognized environment variable","environment-variable":"ETCD_TEST_PORT_2379_TCP_ADDR=10.20.167.3"}
{"level":"warn","ts":1634037928.362907,"caller":"flags/flag.go:93","msg":"unrecognized environment variable","environment-variable":"ETCD_VOLUME_DIR=/bitnami/etcd"}
{"level":"warn","ts":1634037928.362912,"caller":"flags/flag.go:93","msg":"unrecognized environment variable","environment-variable":"ETCD_TEST_SERVICE_PORT_PEER=2380"}
{"level":"warn","ts":1634037928.362918,"caller":"flags/flag.go:93","msg":"unrecognized environment variable","environment-variable":"ETCD_TEST_PORT=tcp://10.20.167.3:2379"}
{"level":"warn","ts":1634037928.3629293,"caller":"flags/flag.go:93","msg":"unrecognized environment variable","environment-variable":"ETCD_CLUSTER_DOMAIN=etcd-test-headless.ng-etcd.svc.cluster.local"}
{"level":"warn","ts":1634037928.3629353,"caller":"flags/flag.go:93","msg":"unrecognized environment variable","environment-variable":"ETCD_DISASTER_RECOVERY=no"}
{"level":"warn","ts":1634037928.3629403,"caller":"flags/flag.go:93","msg":"unrecognized environment variable","environment-variable":"ETCD_TEST_SERVICE_PORT=2379"}
{"level":"warn","ts":1634037928.362946,"caller":"flags/flag.go:93","msg":"unrecognized environment variable","environment-variable":"ETCD_KEY_FILE="}
{"level":"warn","ts":1634037928.3629513,"caller":"flags/flag.go:93","msg":"unrecognized environment variable","environment-variable":"ETCD_TEST_PORT_2380_TCP=tcp://10.20.167.3:2380"}
{"level":"warn","ts":1634037928.3629563,"caller":"flags/flag.go:93","msg":"unrecognized environment variable","environment-variable":"ETCD_TEST_PORT_2379_TCP_PROTO=tcp"}
{"level":"warn","ts":1634037928.3629618,"caller":"flags/flag.go:93","msg":"unrecognized environment variable","environment-variable":"ETCD_DAEMON_GROUP=etcd"}
{"level":"warn","ts":1634037928.3629668,"caller":"flags/flag.go:93","msg":"unrecognized environment variable","environment-variable":"ETCD_START_FROM_SNAPSHOT=no"}
{"level":"warn","ts":1634037928.3629735,"caller":"flags/flag.go:93","msg":"unrecognized environment variable","environment-variable":"ETCD_INIT_SNAPSHOT_FILENAME="}
{"level":"warn","ts":1634037928.3629787,"caller":"flags/flag.go:93","msg":"unrecognized environment variable","environment-variable":"ETCD_INIT_SNAPSHOTS_DIR=/init-snapshot"}
{"level":"warn","ts":1634037928.3629854,"caller":"flags/flag.go:93","msg":"unrecognized environment variable","environment-variable":"ETCD_BASE_DIR=/opt/bitnami/etcd"}
{"level":"warn","ts":1634037928.3629916,"caller":"flags/flag.go:93","msg":"unrecognized environment variable","environment-var [...]

2021-10-20 02:44 UTC, ipleten commented
I just wonder won't it be easier to write member_id if it's empty and persistence is enabled. 
IINM currently it will cause either restoration or log replication if pod were moved to another node no matter it has persistent volume. So why don't just persist everything?

2021-11-05 07:40 UTC, juan131 commented
Still pending an update from my side on this

2021-11-18 12:02 UTC, juan131 approved these changes
Hi everyone, I just submitted a commit targeting a couple of race conditions more. We'll proceed to merge these changes as they're now and we'll continue iterating to improve the logic.

- Does is it mean we addressed all the issues? No, we still need to iterate on new PRs.
- Why do we merge the changes then? Because we need to move forward. This has been blocked for too long and I don't want to block it any longer.

2021-11-18 14:46 UTC, merged

2022-01-13 07:49 UTC, ErikXu commented
I have a cluster but some member_id is lost. Is it possible to write back the  member_id ?