Remove member_id persist & self removal
bitnami/bitnami-docker-etcd pull request #42
Opened 2022-05-22 14:19 UTC by haorenfsa

Signed-off-by: shaoyue.chen <shaoyue.chen@zilliz.com>

**Description of the change**

- Remove the `member_id` persist.
- No self removal when pod stop.

**Benefits**

- Fix `member_id`, `removal log ` persistence issues.
- In kubernetes, you can kill any number of pods, the etcd cluster can always go back to healthy state
- Fix unable to scale up when failed when some pod is down while the etcd cluster is healthy

**Possible drawbacks**

- When shrinking the size of etcd-cluster, one have to manually remove the old members from cluster using `etcdctl member remove`

**Applicable issues**

#39 

**Additional information**

see: #39

2022-05-26 09:13 UTC, jotamartos commented
Hi @haorenfsa,

Thank you for taking the time to create this PR and improve our solution. Without reviewing the code deeply, I can see there is a blocker here that will prevent us from accepting the changes. 

> When shrinking the size of etcd-cluster (aka scale down), one have to manually remove the old members from cluster using etcdctl member remove

Leaving the members information may affect the performance of the deployment and that is not a desired 
configuration. I saw your comment in https://github.com/bitnami/bitnami-docker-etcd/issues/39 but I do not see the benefit of removing this functionality. Could you please provide more details so the team can evaluate properly?  Is there any workaround that can be implemented in the prestop.sh script that makes the self removal process work? 

Thanks

2022-05-26 13:33 UTC, haorenfsa commented
@jotamartos Hi, thank you for taking the time.

Let's start with the benefit of removing the file writing. 
I hope we have an agreement that the current status of etcd helm chart is quite fragile. Once a pod is down in the etcd-cluster, it can seldom rejoin the cluster again. Our team uses etcd as the backbone of our project. In our practice, it happens 9 times out of 10. Not to say when there're 2 or more pods going down together, the cluster easily die on this.

All the problems leads to the file writings. I think we'd better not bet on the files to be written correctly. We either write more complicated mechanism like what databases are doing to ensure the writing, or we prevent to write at all.

Removing the file writing solves the problem in a comparativly simple way. Like I said ahead, the benefit is that `you can kill any number of pods, the etcd cluster can always go back to healthy state. There will be no need for disaster recovery any more.`

And about removing the prestop.  
We should all agree that etcd is design to persist and ensure consistency. While the `prestop`  removes a replica's data in its shutdown, which is quite the opposite. When pods gets shutdown one after another, it's very likely only one replica is kept at last, we may some suffer data loss. And if the final replicas's disk goes down, we lost all data.
Besides the `prestop` hook has a weak guarantee in kubernetes. And it writes a file, we should prevent it.

About the shrinking, current mechanism didn't guarantee shrinking successfully, either. And I just tested with current version , 3 times and it fails every time. We may do this by emitting an extra `Job` everytime we want to shrink. Besides people don't use this in most cases.

2022-05-31 06:31 UTC, ondrej-smola commented
First @haorenfsa thank you for getting to the point and your suggestions. @jotamartos my problem is that chart is rather broken (explained above) and IMHO does not hold to the very high production state of other bitnami charts (and we are using many of them). It is the only chart that we had to replace with custom yaml files. My point is that there may need to be some blocker relaxed as to get it to state when it can be relied on in production. I think the changes suggested will get us much closer to the goal. I am more than happy to help testing it.

2022-06-14 08:22 UTC, jotamartos commented
Hi @haorenfsa  and @ondrej-smola,

Thank you for taking the time to provide this valuable feedback. I created a task on our side to review all this information and to review the PR as well. We will investigate if there is any other improvement we can make to this PR to make the solution more "production ready". I can't provide you with an ETA, but we will notify you with any progress we make. 

Thanks

2022-06-14 08:53 UTC, ondrej-smola commented
@jotamartos thank you very much, just to add my two cents to automatic member removal: I think most users use etcd as critical piece of infrastructure/distributed system. Most installations will be only 5/3/1 member clusters, mostly 3 or 1. The only reasonable action is to switch between 5 and 3 nodes and even in that case it must be ensured that quorum wont be lost (disruption budgets and others). Switching from 3 to 1 node setup is rare and very specific. I think requiring operator to (semi) manually remove members from etcd cluster is the correct way as we are not speaking about gaining performance by adding etcd nodes - we are gaining availability and this is system reliability decision - not some scaling feature that changes often.

2022-06-14 09:32 UTC, haorenfsa commented
@jotamartos yeah, we're testing it, too, and together with the path #44. I'll let you know if we found any problem. I'm also glad to help if there's anything else I can do.

2022-06-20 14:09 UTC, javsalgar commented
Hi,

I've been taking a look and I think it is worth performing these changes. However, as I'm not sure of the potential side effects of breaks in other existing installations, I believe we should have an environment variable that enable or disable the feature:

`ETCD_STORE_MEMBER_ID`: If this variable is true, write the member_id file. In order to not perform a breaking change, default it to true.

In the chart, we can have a value that enables/disables the preStop. 

I think it will be a step forward in the good direction, but for the time being letting users to try and test this feature. If the feedback is positive, we can consider cutting a new major release where we definitely remove all the member_id logic. Thoughts?

2022-06-20 17:53 UTC, haorenfsa commented
I agree. It's a really good idea to make it an option first.

2022-06-21 07:27 UTC, javsalgar commented
Awesome! Will you be able to add this to the PR? If not, we continue the work here

2022-06-21 07:39 UTC, haorenfsa commented
> Awesome! Will you be able to add this to the PR? If not, we continue the work here

Yes, i'm working on it

2022-06-21 12:22 UTC, haorenfsa commented
@javsalgar Hi, I just updated my code. And I haven't got time to test it yet. I sent you an invitation as collaborator of my forked repo, so that you can edit this patch easily, if you need, check your email.

And here are some description about my updates:

I added 2 environment variables: `ETCD_DISABLE_STORE_MEMBER_ID` & `ETCD_DISABLE_PRESTOP` to controll the feature. And I only updated the `/3.3/debian-10/` folder to avoid the copy for now and for the convenience of review.

I use `ETCD_DISABLE_STORE_MEMBER_ID` instead of `ETCD_STORE_MEMBER_ID` so that it is not adopt by default.
And I add the `ETCD_DISABLE_PRESTOP` in case that users not using helm chart or not using the latest chart version want to use this feature.

When both environment vars are not set, it should work in the same machenism before. I'm not pretty sure whether it would work to only enable one of them.

And in fact my path has a third feature you didn't mention: only send requests to alived nodes in cluster when add new member, check the`add_self_to_cluster()`. I'm not sure whether you want to add it in this patch or open another PR for it.

2022-06-22 08:19 UTC, javsalgar commented
The changes look good to me, but I would like to test it in our automated system in case there are issues.

2022-06-22 12:44 UTC, ondrej-smola commented
Will also test it tomorrow

2022-06-22 14:43 UTC, javsalgar commented
Based on the tests I've done so far, it doesn't seem to break

2022-06-22 15:04 UTC, javsalgar requested changes

2022-06-22 15:04 UTC, javsalgar commented on 3.3/debian-10/rootfs/opt/bitnami/scripts/libetcd.sh
> +        if ! -s "${ETCD_DATA_DIR}/member_id" then
Incorrect syntax

2022-06-22 15:04 UTC, javsalgar commented on 3.3/debian-10/rootfs/opt/bitnami/scripts/libetcd.sh
> +    elif [[ ! -d "${ETCD_DATA_DIR}/member/snap" ]] && [[ is_empty_value "$(get_member_id)" ]]; then
Don't use [[ and is_empty_value. Remove the brackets surrounding it

2022-06-23 07:34 UTC, ondrej-smola commented
Based on tests I made so far it broke in one cases out of 8 ... tested 3 and 5 member clusters. The broken test case is really strange to me. In the end it failed on each member generating distinct clusterId with different memberId - log attached. The bad thing is I am unable to reproduce it again :(.

[etcd-test-2.log](https://github.com/bitnami/bitnami-docker-etcd/files/8965027/etcd-test-2.log)

```
global:
  imageRegistry: harbor.ite.tul.cz
extraEnvVars:
  - name: ETCD_DISABLE_STORE_MEMBER_ID
    value: "true"
  - name: ETCD_DISABLE_PRESTOP
    value: "true"
image:  
  repository: library/etcd
  tag: 3.5.4-no-removal
  pullPolicy: Always
auth:
  rbac:
    rootPassword: root
replicaCount: 3
persistence:
  storageClass: ceph-filesystem
```

2022-06-23 07:41 UTC, haorenfsa commented
@ondrej-smola Hi, that's due to the issue that #44 is trying to fix, this happens in current version as well. Use this patch and it shall works fine.

2022-06-23 07:43 UTC, ondrej-smola commented
Rolling updates now just work ... this was the real pain point before :)

2022-06-23 07:44 UTC, ondrej-smola commented
@haorenfsa thanks - missed that one

2022-06-23 08:09 UTC, ondrej-smola commented
Repeated tests - LGMT as long as it is released with #44

2022-06-23 09:58 UTC, merged

2022-06-23 09:59 UTC, javsalgar commented
Thank you so much for the contribution!

2022-07-05 17:31 UTC, arloliu commented
@haorenfsa 
Enable `ETCD_DISABLE_STORE_MEMBER_ID` will cause this.

```
etcd 17:28:24.87 WARN  ==> You set the environment variable ALLOW_NONE_AUTHENTICATION=yes. For safety reasons, do not use this flag in a production environment.                                                                    
│ etcd 17:28:24.87 INFO  ==> Initializing etcd                                                                                                                                                                                        
│ etcd 17:28:24.87 INFO  ==> Generating etcd config file using env variables                                                                                                                                                          
│ etcd 17:28:24.89 INFO  ==> Detected data from previous deployments                                                                                                                                                                  
│ /opt/bitnami/scripts/libetcd.sh: line 752: ETCD_ACTIVE_ENDPOINTS: unbound variable    
```

2022-07-06 06:06 UTC, haorenfsa commented
> @haorenfsa Enable `ETCD_DISABLE_STORE_MEMBER_ID` will cause this.
> 
> ```
> etcd 17:28:24.87 WARN  ==> You set the environment variable ALLOW_NONE_AUTHENTICATION=yes. For safety reasons, do not use this flag in a production environment.                                                                    
> │ etcd 17:28:24.87 INFO  ==> Initializing etcd                                                                                                                                                                                        
> │ etcd 17:28:24.87 INFO  ==> Generating etcd config file using env variables                                                                                                                                                          
> │ etcd 17:28:24.89 INFO  ==> Detected data from previous deployments                                                                                                                                                                  
> │ /opt/bitnami/scripts/libetcd.sh: line 752: ETCD_ACTIVE_ENDPOINTS: unbound variable    
> ```

upgrading case, let's discuss it in #46

2022-07-06 06:09 UTC, haorenfsa commented
And for those who just got here. If you're installing from scratch, I suggest that `ETCD_DISABLE_STORE_MEMBER_ID` & `ETCD_DISABLE_PRESTOP` better be enabled together.