Use sync instead of stdbuf
bitnami/bitnami-docker-etcd pull request #43
Opened 2022-05-22 15:06 UTC by haorenfsa

Signed-off-by: shaoyue.chen <shaoyue.chen@zilliz.com>

**Description of the change**

- use `sync` instead of `stdbuf`

**Benefits**

- Reduce the chances that `member_id` & `member_removal.log` files are not being persisted

**Possible drawbacks**

**Applicable issues**

#39

**Additional information**

2022-05-25 10:07 UTC, joancafom requested changes
Thanks so much for your PR @haorenfsa ! I left you a couple of comments, could you please review them?

2022-05-25 10:07 UTC, joancafom commented on 3.3/debian-10/rootfs/opt/bitnami/scripts/libetcd.sh
> +            member_id=etcdctl "${extra_flags[@]}" member list | grep -w "${advertised_array[0]}" | awk -F "," '{ print $1}' || true
We usually make use of sub-shells to assign values to existing variables. IMHO, it is easier to read.

```suggestion
            member_id="$(etcdctl "${extra_flags[@]}" member list | grep -w "${advertised_array[0]}" | awk -F "," '{ print $1}' || true)"
```

2022-05-25 10:23 UTC, haorenfsa commented
> Thanks so much for your PR @haorenfsa ! I left you a couple of comments, could you please review them?

Thank you. It's updated.

2022-05-25 13:24 UTC, haorenfsa commented
@joancafom All updated

2022-05-30 14:27 UTC, joancafom commented
Hi again @haorenfsa 

Changes LGTM now. As this logic might seem trivial, I want to ensure that the use of `sync` does not come with side effects. I will test the changes internally and come back soon, either to provide further feedback or to give the green light and merge this. 

> Btw, what do you think about the other PR?

As regards this, I did not have time to review it yet. The changes there do not seem to be trivial, so in the meantime, I consider we may resort to this PR `sync` and see how that handles the file persistence issue.

2022-05-30 15:31 UTC, joancafom requested changes
Some feedback coming from the testing phase 😁

2022-05-30 15:31 UTC, joancafom commented on 3.3/debian-10/rootfs/opt/bitnami/scripts/libetcd.sh
> +        while is_empty_value "${member_id}"; do
```suggestion
        while is_empty_value "$member_id"; do
```

2022-05-30 15:33 UTC, joancafom commented on 3.3/debian-10/rootfs/opt/bitnami/scripts/libetcd.sh
> +    local member_id
You need to assign it an initial value, else the script will fail with `member_id: unbound variable` on line 315.

```suggestion
    local member_id=""
```


You need to assign an initial value, else bash will report `member_id: unbound variable` on line 315.

2022-05-31 05:02 UTC, haorenfsa commented
Updated

2022-06-01 17:19 UTC, merged