FIx ETCD_ACTIVE_ENDPOINTS environment variable not found issue
bitnami/bitnami-docker-etcd pull request #49
Opened 2022-07-05 19:35 UTC by arloliu

**Description of the change**
Fix the issue created by PR https://github.com/bitnami/bitnami-docker-etcd/pull/42
Create a `setup_etcd_active_endpoints` function to  set `ETCD_ACTIVE_ENDPOINTS` env.

And call this function in `get_member_id` function.

**Benefits**

Fix etcd startup issue if `ETCD_DISABLE_STORE_MEMBER_ID` set to `yes`

**Possible drawbacks**
None

**Applicable issues**

**Additional information**
PR https://github.com/bitnami/bitnami-docker-etcd/pull/42

2022-07-06 05:53 UTC, haorenfsa commented
Hi, it seems that you're upgrading from a previous release with `ETCD_DISABLE_STORE_MEMBER_ID` set to `yes`.
Unfortunately, current image does not support upgrading from previous release. I'm still working on it see: issue #46.

2022-07-06 06:03 UTC, haorenfsa commented
This patch alone looks good to me, though.

2022-07-06 15:04 UTC, arloliu commented
thanks, I think disabling the member id store and letting the pod to re-join itself is a better approach than managing the member id in each pod.

2022-07-07 01:11 UTC, nschimke commented on 3.3/debian-11/rootfs/opt/bitnami/scripts/libetcd.sh
> +is_healthy_etcd_cluster() {
This function references $cluster_size which is undefined here after this change.

2022-07-08 00:41 UTC, arloliu commented on 3.3/debian-11/rootfs/opt/bitnami/scripts/libetcd.sh
> +is_healthy_etcd_cluster() {
Thanks a lot, I fixed it, please help to review

2022-07-09 20:50 UTC, arloliu commented
Sure,  I created a local docker image `etcd:test2`, set it to etcd helm chart with the following options:
1. set env var `ETCD_DISABLE_STORE_MEMBER_ID` to `yes`
2. set `removeMemberOnContainerTermination` to `false` (It will not call `preStop` script that removes member from cluster)

And I tested 2 cases
1. Delete `/bitnami/etcd/data/member_id` manually before rolling restart etcd statefulset
2. Keep `/bitnami/etcd/data/member_id`

The line of log below indicating the `get_member_id` function fetch member if from `etcdctl member list` successfully and it doesn't have unbound `ETCD_ACTIVE_ENDPOINTS` issue
```
etcd 20:26:28.37 INFO  ==> member id: 45a18acb10aa275e
```
**Stateful screenshot**
![image](https://user-images.githubusercontent.com/1687357/178121746-f52b0dd7-bf5e-4120-9894-e074b766adf8.png)

**Pod log**
![image](https://user-images.githubusercontent.com/1687357/178121821-b2ff4ab1-31ee-4e61-b50a-5fdd4569685f.png)

2022-07-11 17:05 UTC, arloliu commented on 3.3/debian-11/rootfs/opt/bitnami/scripts/libetcd.sh
> +    if [ -z ${etcd_active_endpoints} ]; then
ok, let me test if is_empty_value works

2022-07-12 02:30 UTC, haorenfsa commented
Looks good! @arloliu So have you succeeded in upgrading from earlier release to disabled member_id store & prestop with this patch?

2022-07-13 11:20 UTC, javsalgar requested changes
Small change requested!

2022-07-13 11:20 UTC, javsalgar commented on 3.5/debian-11/rootfs/opt/bitnami/scripts/libetcd.sh
> -                info "Updating member in existing cluster"
Same here

2022-07-14 05:37 UTC, arloliu commented on 3.4/debian-11/rootfs/opt/bitnami/scripts/libetcd.sh
> -                info "Updating member in existing cluster"
updated

2022-07-14 05:37 UTC, arloliu commented on 3.5/debian-11/rootfs/opt/bitnami/scripts/libetcd.sh
> -                info "Updating member in existing cluster"
updated

2022-07-14 09:57 UTC, javsalgar approved these changes

2022-07-14 09:57 UTC, merged